apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
  MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
  MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="